name = "YcYc for prismatic channels"
description = "Calculates normal and critical depth in prismatic channels as trapezoids, rectangles, triangles and ditches."
packages = ["numpy", "sympy"]

[files]
"./libraries.py" = ""
"./dictionary.py" = ""
